name: learn-github-actions
on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: "A persons name"
        required: true
        default: "Taylor"
      home:
        description: "A persons home"
        required: true
        default: "Sioux Falls"
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats
      - run: bats -v
      - run: echo "name: ${INPUT_NAME}, home: ${INPUT_HOME}"
